/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AAD {
  'id' : RigId,
  'serviceDate' : string,
  'manufacturer' : string,
  'aadType' : string,
  'endOfLife' : string,
  'serialNumber' : string,
  'dateOfManufacture' : string,
}
export type CheckId = bigint;
export type ExternalBlob = Uint8Array;
export interface FiftyJumpCheck {
  'id' : CheckId,
  'completedDate' : string,
  'completedBy' : string,
  'checklistData' : string,
  'createdAt' : bigint,
  'signatureData' : string,
  'notes' : string,
  'rigId' : RigId,
}
export interface FiftyJumpCheckInput {
  'completedDate' : string,
  'completedBy' : string,
  'checklistData' : string,
  'signatureData' : string,
  'notes' : string,
  'rigId' : RigId,
}
export interface HarnessContainer {
  'id' : RigId,
  'model' : string,
  'manufacturer' : string,
  'serialNumber' : string,
  'dateOfManufacture' : string,
  'image' : [] | [ExternalBlob],
}
export type JumpId = bigint;
export interface MainCanopy {
  'id' : RigId,
  'manufacturer' : string,
  'totalJumps' : bigint,
  'jumpsOnMainRisers' : bigint,
  'canopyType' : string,
  'serialNumber' : string,
  'dateOfManufacture' : string,
  'image' : [] | [ExternalBlob],
  'jumpsOnLineSet' : bigint,
}
export interface MainCanopyInput {
  'id' : RigId,
  'manufacturer' : string,
  'totalJumps' : bigint,
  'jumpsOnMainRisers' : bigint,
  'canopyType' : string,
  'serialNumber' : string,
  'dateOfManufacture' : string,
  'image' : [] | [ExternalBlob],
  'jumpsOnLineSet' : bigint,
}
export interface MainCanopyJumpsInput {
  'id' : bigint,
  'totalJumps' : bigint,
  'jumpsOnMainRisers' : bigint,
  'jumpsOnLineSet' : bigint,
}
export type NoteId = bigint;
export interface PackJob {
  'id' : JumpId,
  'packDate' : string,
  'createdAt' : bigint,
  'signatureData' : string,
  'packerName' : string,
  'rigId' : RigId,
}
export interface ReserveCanopy {
  'id' : RigId,
  'manufacturer' : string,
  'expiryDate' : string,
  'totalJumps' : bigint,
  'dateRepacked' : string,
  'serialNumber' : string,
  'reserveType' : string,
  'dateOfManufacture' : string,
}
export interface ReserveRepackInput {
  'id' : RigId,
  'manufacturer' : string,
  'totalJumps' : bigint,
  'dateRepacked' : string,
  'serialNumber' : string,
  'reserveType' : string,
  'dateOfManufacture' : string,
}
export interface Rig {
  'id' : RigId,
  'aad' : [] | [AAD],
  'mainCanopy' : [] | [MainCanopy],
  'ownerName' : string,
  'jumpsSinceLastCheck' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'totalJumps' : bigint,
  'reserveCanopy' : [] | [ReserveCanopy],
  'updatedAt' : bigint,
  'harnessContainer' : [] | [HarnessContainer],
  'tandemCanopy' : [] | [TandemMainCanopy],
}
export interface RigComponents {
  'aad' : [] | [AAD],
  'mainCanopy' : [] | [MainCanopy],
  'reserveCanopy' : [] | [ReserveCanopy],
  'harnessContainer' : [] | [HarnessContainer],
  'tandemCanopy' : [] | [TandemMainCanopy],
}
export type RigId = bigint;
export interface RigUpdateInput {
  'id' : RigId,
  'ownerName' : string,
  'name' : string,
  'totalJumps' : bigint,
}
export interface RiggerNote {
  'id' : NoteId,
  'note' : string,
  'createdAt' : bigint,
  'rigId' : RigId,
  'componentType' : string,
}
export interface TandemCanopyInput {
  'id' : RigId,
  'manufacturer' : string,
  'jumpsOnDrogueBridle' : bigint,
  'totalJumps' : bigint,
  'jumpsOnMainRisers' : bigint,
  'canopyType' : string,
  'serialNumber' : string,
  'dateOfManufacture' : string,
  'image' : [] | [ExternalBlob],
  'jumpsOnLowerBridleKillLine' : bigint,
  'jumpsOnLineSet' : bigint,
}
export interface TandemCanopyJumpsInput {
  'id' : bigint,
  'jumpsOnDrogueBridle' : bigint,
  'totalJumps' : bigint,
  'jumpsOnMainRisers' : bigint,
  'jumpsOnLowerBridleKillLine' : bigint,
  'jumpsOnLineSet' : bigint,
}
export interface TandemMainCanopy {
  'id' : RigId,
  'manufacturer' : string,
  'jumpsOnDrogueBridle' : bigint,
  'totalJumps' : bigint,
  'jumpsOnMainRisers' : bigint,
  'canopyType' : string,
  'serialNumber' : string,
  'dateOfManufacture' : string,
  'image' : [] | [ExternalBlob],
  'jumpsOnLowerBridleKillLine' : bigint,
  'jumpsOnLineSet' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addHarnessImage' : ActorMethod<
    [RigId, ExternalBlob],
    [] | [HarnessContainer]
  >,
  'addPackJob' : ActorMethod<[RigId, string, string, string], [] | [PackJob]>,
  'addRiggerNote' : ActorMethod<[RigId, string, string], [] | [RiggerNote]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeFiftyJumpCheck' : ActorMethod<
    [FiftyJumpCheckInput],
    [] | [FiftyJumpCheck]
  >,
  'createRig' : ActorMethod<[string, string], Rig>,
  'deleteRig' : ActorMethod<[RigId], boolean>,
  'deletePackJob' : ActorMethod<[JumpId], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFiftyJumpChecks' : ActorMethod<[RigId], Array<FiftyJumpCheck>>,
  'getPackJobs' : ActorMethod<[RigId], Array<PackJob>>,
  'getRig' : ActorMethod<[RigId], [] | [Rig]>,
  'getRigComponents' : ActorMethod<[RigId], [] | [RigComponents]>,
  'getRiggerNotes' : ActorMethod<[RigId], Array<RiggerNote>>,
  'getRigs' : ActorMethod<[], Array<Rig>>,
  'getRigsByUser' : ActorMethod<[string], Array<Rig>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeAAD' : ActorMethod<[RigId], boolean>,
  'removeHarnessContainer' : ActorMethod<[RigId], boolean>,
  'removeMainCanopy' : ActorMethod<[RigId], boolean>,
  'removeReserveCanopy' : ActorMethod<[RigId], boolean>,
  'removeTandemMainCanopy' : ActorMethod<[RigId], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAAD' : ActorMethod<[AAD], boolean>,
  'setHarnessContainer' : ActorMethod<[HarnessContainer], boolean>,
  'setMainCanopy' : ActorMethod<[MainCanopyInput], boolean>,
  'setReserveCanopy' : ActorMethod<[ReserveRepackInput], boolean>,
  'setTandemMainCanopy' : ActorMethod<[TandemCanopyInput], boolean>,
  'updateMainCanopyJumps' : ActorMethod<[MainCanopyJumpsInput], boolean>,
  'updateRig' : ActorMethod<[[] | [RigUpdateInput]], [] | [Rig]>,
  'updateTandemMainCanopyJumps' : ActorMethod<
    [TandemCanopyJumpsInput],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];