/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const RigId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const HarnessContainer = IDL.Record({
  'id' : RigId,
  'model' : IDL.Text,
  'manufacturer' : IDL.Text,
  'serialNumber' : IDL.Text,
  'dateOfManufacture' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const JumpId = IDL.Nat;
export const PackJob = IDL.Record({
  'id' : JumpId,
  'packDate' : IDL.Text,
  'createdAt' : IDL.Int,
  'signatureData' : IDL.Text,
  'packerName' : IDL.Text,
  'rigId' : RigId,
});
export const NoteId = IDL.Nat;
export const RiggerNote = IDL.Record({
  'id' : NoteId,
  'note' : IDL.Text,
  'createdAt' : IDL.Int,
  'rigId' : RigId,
  'componentType' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FiftyJumpCheckInput = IDL.Record({
  'completedDate' : IDL.Text,
  'completedBy' : IDL.Text,
  'checklistData' : IDL.Text,
  'signatureData' : IDL.Text,
  'notes' : IDL.Text,
  'rigId' : RigId,
});
export const CheckId = IDL.Nat;
export const FiftyJumpCheck = IDL.Record({
  'id' : CheckId,
  'completedDate' : IDL.Text,
  'completedBy' : IDL.Text,
  'checklistData' : IDL.Text,
  'createdAt' : IDL.Int,
  'signatureData' : IDL.Text,
  'notes' : IDL.Text,
  'rigId' : RigId,
});
export const AAD = IDL.Record({
  'id' : RigId,
  'serviceDate' : IDL.Text,
  'manufacturer' : IDL.Text,
  'aadType' : IDL.Text,
  'endOfLife' : IDL.Text,
  'serialNumber' : IDL.Text,
  'dateOfManufacture' : IDL.Text,
});
export const MainCanopy = IDL.Record({
  'id' : RigId,
  'manufacturer' : IDL.Text,
  'totalJumps' : IDL.Nat,
  'jumpsOnMainRisers' : IDL.Nat,
  'canopyType' : IDL.Text,
  'serialNumber' : IDL.Text,
  'dateOfManufacture' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'jumpsOnLineSet' : IDL.Nat,
});
export const ReserveCanopy = IDL.Record({
  'id' : RigId,
  'manufacturer' : IDL.Text,
  'expiryDate' : IDL.Text,
  'totalJumps' : IDL.Nat,
  'dateRepacked' : IDL.Text,
  'serialNumber' : IDL.Text,
  'reserveType' : IDL.Text,
  'dateOfManufacture' : IDL.Text,
});
export const TandemMainCanopy = IDL.Record({
  'id' : RigId,
  'manufacturer' : IDL.Text,
  'jumpsOnDrogueBridle' : IDL.Nat,
  'totalJumps' : IDL.Nat,
  'jumpsOnMainRisers' : IDL.Nat,
  'canopyType' : IDL.Text,
  'serialNumber' : IDL.Text,
  'dateOfManufacture' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'jumpsOnLowerBridleKillLine' : IDL.Nat,
  'jumpsOnLineSet' : IDL.Nat,
});
export const Rig = IDL.Record({
  'id' : RigId,
  'aad' : IDL.Opt(AAD),
  'mainCanopy' : IDL.Opt(MainCanopy),
  'ownerName' : IDL.Text,
  'jumpsSinceLastCheck' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'totalJumps' : IDL.Nat,
  'reserveCanopy' : IDL.Opt(ReserveCanopy),
  'updatedAt' : IDL.Int,
  'harnessContainer' : IDL.Opt(HarnessContainer),
  'tandemCanopy' : IDL.Opt(TandemMainCanopy),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const RigComponents = IDL.Record({
  'aad' : IDL.Opt(AAD),
  'mainCanopy' : IDL.Opt(MainCanopy),
  'reserveCanopy' : IDL.Opt(ReserveCanopy),
  'harnessContainer' : IDL.Opt(HarnessContainer),
  'tandemCanopy' : IDL.Opt(TandemMainCanopy),
});
export const MainCanopyInput = IDL.Record({
  'id' : RigId,
  'manufacturer' : IDL.Text,
  'totalJumps' : IDL.Nat,
  'jumpsOnMainRisers' : IDL.Nat,
  'canopyType' : IDL.Text,
  'serialNumber' : IDL.Text,
  'dateOfManufacture' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'jumpsOnLineSet' : IDL.Nat,
});
export const ReserveRepackInput = IDL.Record({
  'id' : RigId,
  'manufacturer' : IDL.Text,
  'totalJumps' : IDL.Nat,
  'dateRepacked' : IDL.Text,
  'serialNumber' : IDL.Text,
  'reserveType' : IDL.Text,
  'dateOfManufacture' : IDL.Text,
});
export const TandemCanopyInput = IDL.Record({
  'id' : RigId,
  'manufacturer' : IDL.Text,
  'jumpsOnDrogueBridle' : IDL.Nat,
  'totalJumps' : IDL.Nat,
  'jumpsOnMainRisers' : IDL.Nat,
  'canopyType' : IDL.Text,
  'serialNumber' : IDL.Text,
  'dateOfManufacture' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'jumpsOnLowerBridleKillLine' : IDL.Nat,
  'jumpsOnLineSet' : IDL.Nat,
});
export const MainCanopyJumpsInput = IDL.Record({
  'id' : IDL.Nat,
  'totalJumps' : IDL.Nat,
  'jumpsOnMainRisers' : IDL.Nat,
  'jumpsOnLineSet' : IDL.Nat,
});
export const RigUpdateInput = IDL.Record({
  'id' : RigId,
  'ownerName' : IDL.Text,
  'name' : IDL.Text,
  'totalJumps' : IDL.Nat,
});
export const TandemCanopyJumpsInput = IDL.Record({
  'id' : IDL.Nat,
  'jumpsOnDrogueBridle' : IDL.Nat,
  'totalJumps' : IDL.Nat,
  'jumpsOnMainRisers' : IDL.Nat,
  'jumpsOnLowerBridleKillLine' : IDL.Nat,
  'jumpsOnLineSet' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addHarnessImage' : IDL.Func(
      [RigId, ExternalBlob],
      [IDL.Opt(HarnessContainer)],
      [],
    ),
  'addPackJob' : IDL.Func(
      [RigId, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(PackJob)],
      [],
    ),
  'addRiggerNote' : IDL.Func(
      [RigId, IDL.Text, IDL.Text],
      [IDL.Opt(RiggerNote)],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeFiftyJumpCheck' : IDL.Func(
      [FiftyJumpCheckInput],
      [IDL.Opt(FiftyJumpCheck)],
      [],
    ),
  'createRig' : IDL.Func([IDL.Text, IDL.Text], [Rig], []),
  'deleteRig' : IDL.Func([RigId], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFiftyJumpChecks' : IDL.Func(
      [RigId],
      [IDL.Vec(FiftyJumpCheck)],
      ['query'],
    ),
  'getPackJobs' : IDL.Func([RigId], [IDL.Vec(PackJob)], ['query']),
  'getRig' : IDL.Func([RigId], [IDL.Opt(Rig)], ['query']),
  'getRigComponents' : IDL.Func([RigId], [IDL.Opt(RigComponents)], ['query']),
  'getRiggerNotes' : IDL.Func([RigId], [IDL.Vec(RiggerNote)], ['query']),
  'getRigs' : IDL.Func([], [IDL.Vec(Rig)], ['query']),
  'getRigsByUser' : IDL.Func([IDL.Text], [IDL.Vec(Rig)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeAAD' : IDL.Func([RigId], [IDL.Bool], []),
  'removeHarnessContainer' : IDL.Func([RigId], [IDL.Bool], []),
  'removeMainCanopy' : IDL.Func([RigId], [IDL.Bool], []),
  'removeReserveCanopy' : IDL.Func([RigId], [IDL.Bool], []),
  'removeTandemMainCanopy' : IDL.Func([RigId], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAAD' : IDL.Func([AAD], [IDL.Bool], []),
  'setHarnessContainer' : IDL.Func([HarnessContainer], [IDL.Bool], []),
  'setMainCanopy' : IDL.Func([MainCanopyInput], [IDL.Bool], []),
  'setReserveCanopy' : IDL.Func([ReserveRepackInput], [IDL.Bool], []),
  'setTandemMainCanopy' : IDL.Func([TandemCanopyInput], [IDL.Bool], []),
  'updateMainCanopyJumps' : IDL.Func([MainCanopyJumpsInput], [IDL.Bool], []),
  'updateRig' : IDL.Func([IDL.Opt(RigUpdateInput)], [IDL.Opt(Rig)], []),
  'updateTandemMainCanopyJumps' : IDL.Func(
      [TandemCanopyJumpsInput],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const RigId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const HarnessContainer = IDL.Record({
    'id' : RigId,
    'model' : IDL.Text,
    'manufacturer' : IDL.Text,
    'serialNumber' : IDL.Text,
    'dateOfManufacture' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const JumpId = IDL.Nat;
  const PackJob = IDL.Record({
    'id' : JumpId,
    'packDate' : IDL.Text,
    'createdAt' : IDL.Int,
    'signatureData' : IDL.Text,
    'packerName' : IDL.Text,
    'rigId' : RigId,
  });
  const NoteId = IDL.Nat;
  const RiggerNote = IDL.Record({
    'id' : NoteId,
    'note' : IDL.Text,
    'createdAt' : IDL.Int,
    'rigId' : RigId,
    'componentType' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FiftyJumpCheckInput = IDL.Record({
    'completedDate' : IDL.Text,
    'completedBy' : IDL.Text,
    'checklistData' : IDL.Text,
    'signatureData' : IDL.Text,
    'notes' : IDL.Text,
    'rigId' : RigId,
  });
  const CheckId = IDL.Nat;
  const FiftyJumpCheck = IDL.Record({
    'id' : CheckId,
    'completedDate' : IDL.Text,
    'completedBy' : IDL.Text,
    'checklistData' : IDL.Text,
    'createdAt' : IDL.Int,
    'signatureData' : IDL.Text,
    'notes' : IDL.Text,
    'rigId' : RigId,
  });
  const AAD = IDL.Record({
    'id' : RigId,
    'serviceDate' : IDL.Text,
    'manufacturer' : IDL.Text,
    'aadType' : IDL.Text,
    'endOfLife' : IDL.Text,
    'serialNumber' : IDL.Text,
    'dateOfManufacture' : IDL.Text,
  });
  const MainCanopy = IDL.Record({
    'id' : RigId,
    'manufacturer' : IDL.Text,
    'totalJumps' : IDL.Nat,
    'jumpsOnMainRisers' : IDL.Nat,
    'canopyType' : IDL.Text,
    'serialNumber' : IDL.Text,
    'dateOfManufacture' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'jumpsOnLineSet' : IDL.Nat,
  });
  const ReserveCanopy = IDL.Record({
    'id' : RigId,
    'manufacturer' : IDL.Text,
    'expiryDate' : IDL.Text,
    'totalJumps' : IDL.Nat,
    'dateRepacked' : IDL.Text,
    'serialNumber' : IDL.Text,
    'reserveType' : IDL.Text,
    'dateOfManufacture' : IDL.Text,
  });
  const TandemMainCanopy = IDL.Record({
    'id' : RigId,
    'manufacturer' : IDL.Text,
    'jumpsOnDrogueBridle' : IDL.Nat,
    'totalJumps' : IDL.Nat,
    'jumpsOnMainRisers' : IDL.Nat,
    'canopyType' : IDL.Text,
    'serialNumber' : IDL.Text,
    'dateOfManufacture' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'jumpsOnLowerBridleKillLine' : IDL.Nat,
    'jumpsOnLineSet' : IDL.Nat,
  });
  const Rig = IDL.Record({
    'id' : RigId,
    'aad' : IDL.Opt(AAD),
    'mainCanopy' : IDL.Opt(MainCanopy),
    'ownerName' : IDL.Text,
    'jumpsSinceLastCheck' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'totalJumps' : IDL.Nat,
    'reserveCanopy' : IDL.Opt(ReserveCanopy),
    'updatedAt' : IDL.Int,
    'harnessContainer' : IDL.Opt(HarnessContainer),
    'tandemCanopy' : IDL.Opt(TandemMainCanopy),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const RigComponents = IDL.Record({
    'aad' : IDL.Opt(AAD),
    'mainCanopy' : IDL.Opt(MainCanopy),
    'reserveCanopy' : IDL.Opt(ReserveCanopy),
    'harnessContainer' : IDL.Opt(HarnessContainer),
    'tandemCanopy' : IDL.Opt(TandemMainCanopy),
  });
  const MainCanopyInput = IDL.Record({
    'id' : RigId,
    'manufacturer' : IDL.Text,
    'totalJumps' : IDL.Nat,
    'jumpsOnMainRisers' : IDL.Nat,
    'canopyType' : IDL.Text,
    'serialNumber' : IDL.Text,
    'dateOfManufacture' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'jumpsOnLineSet' : IDL.Nat,
  });
  const ReserveRepackInput = IDL.Record({
    'id' : RigId,
    'manufacturer' : IDL.Text,
    'totalJumps' : IDL.Nat,
    'dateRepacked' : IDL.Text,
    'serialNumber' : IDL.Text,
    'reserveType' : IDL.Text,
    'dateOfManufacture' : IDL.Text,
  });
  const TandemCanopyInput = IDL.Record({
    'id' : RigId,
    'manufacturer' : IDL.Text,
    'jumpsOnDrogueBridle' : IDL.Nat,
    'totalJumps' : IDL.Nat,
    'jumpsOnMainRisers' : IDL.Nat,
    'canopyType' : IDL.Text,
    'serialNumber' : IDL.Text,
    'dateOfManufacture' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'jumpsOnLowerBridleKillLine' : IDL.Nat,
    'jumpsOnLineSet' : IDL.Nat,
  });
  const MainCanopyJumpsInput = IDL.Record({
    'id' : IDL.Nat,
    'totalJumps' : IDL.Nat,
    'jumpsOnMainRisers' : IDL.Nat,
    'jumpsOnLineSet' : IDL.Nat,
  });
  const RigUpdateInput = IDL.Record({
    'id' : RigId,
    'ownerName' : IDL.Text,
    'name' : IDL.Text,
    'totalJumps' : IDL.Nat,
  });
  const TandemCanopyJumpsInput = IDL.Record({
    'id' : IDL.Nat,
    'jumpsOnDrogueBridle' : IDL.Nat,
    'totalJumps' : IDL.Nat,
    'jumpsOnMainRisers' : IDL.Nat,
    'jumpsOnLowerBridleKillLine' : IDL.Nat,
    'jumpsOnLineSet' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addHarnessImage' : IDL.Func(
        [RigId, ExternalBlob],
        [IDL.Opt(HarnessContainer)],
        [],
      ),
    'addPackJob' : IDL.Func(
        [RigId, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(PackJob)],
        [],
      ),
    'addRiggerNote' : IDL.Func(
        [RigId, IDL.Text, IDL.Text],
        [IDL.Opt(RiggerNote)],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeFiftyJumpCheck' : IDL.Func(
        [FiftyJumpCheckInput],
        [IDL.Opt(FiftyJumpCheck)],
        [],
      ),
    'createRig' : IDL.Func([IDL.Text, IDL.Text], [Rig], []),
    'deleteRig' : IDL.Func([RigId], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFiftyJumpChecks' : IDL.Func(
        [RigId],
        [IDL.Vec(FiftyJumpCheck)],
        ['query'],
      ),
    'getPackJobs' : IDL.Func([RigId], [IDL.Vec(PackJob)], ['query']),
    'getRig' : IDL.Func([RigId], [IDL.Opt(Rig)], ['query']),
    'getRigComponents' : IDL.Func([RigId], [IDL.Opt(RigComponents)], ['query']),
    'getRiggerNotes' : IDL.Func([RigId], [IDL.Vec(RiggerNote)], ['query']),
    'getRigs' : IDL.Func([], [IDL.Vec(Rig)], ['query']),
    'getRigsByUser' : IDL.Func([IDL.Text], [IDL.Vec(Rig)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeAAD' : IDL.Func([RigId], [IDL.Bool], []),
    'removeHarnessContainer' : IDL.Func([RigId], [IDL.Bool], []),
    'removeMainCanopy' : IDL.Func([RigId], [IDL.Bool], []),
    'removeReserveCanopy' : IDL.Func([RigId], [IDL.Bool], []),
    'removeTandemMainCanopy' : IDL.Func([RigId], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAAD' : IDL.Func([AAD], [IDL.Bool], []),
    'setHarnessContainer' : IDL.Func([HarnessContainer], [IDL.Bool], []),
    'setMainCanopy' : IDL.Func([MainCanopyInput], [IDL.Bool], []),
    'setReserveCanopy' : IDL.Func([ReserveRepackInput], [IDL.Bool], []),
    'setTandemMainCanopy' : IDL.Func([TandemCanopyInput], [IDL.Bool], []),
    'updateMainCanopyJumps' : IDL.Func([MainCanopyJumpsInput], [IDL.Bool], []),
    'updateRig' : IDL.Func([IDL.Opt(RigUpdateInput)], [IDL.Opt(Rig)], []),
    'updateTandemMainCanopyJumps' : IDL.Func(
        [TandemCanopyJumpsInput],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };