/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ReserveCanopy {
    id: RigId;
    manufacturer: string;
    expiryDate: string;
    totalJumps: bigint;
    dateRepacked: string;
    serialNumber: string;
    reserveType: string;
    dateOfManufacture: string;
}
export type NoteId = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PackJob {
    id: JumpId;
    packDate: string;
    createdAt: bigint;
    signatureData: string;
    packerName: string;
    rigId: RigId;
}
export interface MainCanopy {
    id: RigId;
    manufacturer: string;
    totalJumps: bigint;
    jumpsOnMainRisers: bigint;
    canopyType: string;
    serialNumber: string;
    dateOfManufacture: string;
    image?: ExternalBlob;
    jumpsOnLineSet: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface MainCanopyJumpsInput {
    id: bigint;
    totalJumps: bigint;
    jumpsOnMainRisers: bigint;
    jumpsOnLineSet: bigint;
}
export type CheckId = bigint;
export interface Rig {
    id: RigId;
    aad?: AAD;
    mainCanopy?: MainCanopy;
    ownerName: string;
    jumpsSinceLastCheck: bigint;
    name: string;
    createdAt: bigint;
    totalJumps: bigint;
    reserveCanopy?: ReserveCanopy;
    updatedAt: bigint;
    harnessContainer?: HarnessContainer;
    tandemCanopy?: TandemMainCanopy;
}
export type RigId = bigint;
export interface MainCanopyInput {
    id: RigId;
    manufacturer: string;
    totalJumps: bigint;
    jumpsOnMainRisers: bigint;
    canopyType: string;
    serialNumber: string;
    dateOfManufacture: string;
    image?: ExternalBlob;
    jumpsOnLineSet: bigint;
}
export interface TandemCanopyInput {
    id: RigId;
    manufacturer: string;
    jumpsOnDrogueBridle: bigint;
    totalJumps: bigint;
    jumpsOnMainRisers: bigint;
    canopyType: string;
    serialNumber: string;
    dateOfManufacture: string;
    image?: ExternalBlob;
    jumpsOnLowerBridleKillLine: bigint;
    jumpsOnLineSet: bigint;
}
export interface FiftyJumpCheckInput {
    completedDate: string;
    completedBy: string;
    checklistData: string;
    signatureData: string;
    notes: string;
    rigId: RigId;
}
export interface TandemCanopyJumpsInput {
    id: bigint;
    jumpsOnDrogueBridle: bigint;
    totalJumps: bigint;
    jumpsOnMainRisers: bigint;
    jumpsOnLowerBridleKillLine: bigint;
    jumpsOnLineSet: bigint;
}
export interface RigComponents {
    aad?: AAD;
    mainCanopy?: MainCanopy;
    reserveCanopy?: ReserveCanopy;
    harnessContainer?: HarnessContainer;
    tandemCanopy?: TandemMainCanopy;
}
export interface ReserveRepackInput {
    id: RigId;
    manufacturer: string;
    totalJumps: bigint;
    dateRepacked: string;
    serialNumber: string;
    reserveType: string;
    dateOfManufacture: string;
}
export type JumpId = bigint;
export interface RiggerNote {
    id: NoteId;
    note: string;
    createdAt: bigint;
    rigId: RigId;
    componentType: string;
}
export interface TandemMainCanopy {
    id: RigId;
    manufacturer: string;
    jumpsOnDrogueBridle: bigint;
    totalJumps: bigint;
    jumpsOnMainRisers: bigint;
    canopyType: string;
    serialNumber: string;
    dateOfManufacture: string;
    image?: ExternalBlob;
    jumpsOnLowerBridleKillLine: bigint;
    jumpsOnLineSet: bigint;
}
export interface RigUpdateInput {
    id: RigId;
    ownerName: string;
    name: string;
    totalJumps: bigint;
}
export interface HarnessContainer {
    id: RigId;
    model: string;
    manufacturer: string;
    serialNumber: string;
    dateOfManufacture: string;
    image?: ExternalBlob;
}
export interface FiftyJumpCheck {
    id: CheckId;
    completedDate: string;
    completedBy: string;
    checklistData: string;
    createdAt: bigint;
    signatureData: string;
    notes: string;
    rigId: RigId;
}
export interface AAD {
    id: RigId;
    serviceDate: string;
    manufacturer: string;
    aadType: string;
    endOfLife: string;
    serialNumber: string;
    dateOfManufacture: string;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addHarnessImage(id: RigId, input: ExternalBlob): Promise<HarnessContainer | null>;
    addPackJob(rigId: RigId, packerName: string, signatureData: string, packDate: string): Promise<PackJob | null>;
    addRiggerNote(rigId: RigId, componentType: string, note: string): Promise<RiggerNote | null>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeFiftyJumpCheck(input: FiftyJumpCheckInput): Promise<FiftyJumpCheck | null>;
    createRig(name: string, ownerName: string): Promise<Rig>;
    deleteRig(rigId: RigId): Promise<boolean>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFiftyJumpChecks(rigId: RigId): Promise<Array<FiftyJumpCheck>>;
    getPackJobs(rigId: RigId): Promise<Array<PackJob>>;
    getRig(id: RigId): Promise<Rig | null>;
    getRigComponents(rigId: RigId): Promise<RigComponents | null>;
    getRiggerNotes(rigId: RigId): Promise<Array<RiggerNote>>;
    getRigs(): Promise<Array<Rig>>;
    getRigsByUser(username: string): Promise<Array<Rig>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    removeAAD(id: RigId): Promise<boolean>;
    removeHarnessContainer(rigId: RigId): Promise<boolean>;
    removeMainCanopy(id: RigId): Promise<boolean>;
    removeReserveCanopy(id: RigId): Promise<boolean>;
    removeTandemMainCanopy(id: RigId): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setAAD(input: AAD): Promise<boolean>;
    setHarnessContainer(input: HarnessContainer): Promise<boolean>;
    setMainCanopy(input: MainCanopyInput): Promise<boolean>;
    setReserveCanopy(input: ReserveRepackInput): Promise<boolean>;
    setTandemMainCanopy(input: TandemCanopyInput): Promise<boolean>;
    updateMainCanopyJumps(input: MainCanopyJumpsInput): Promise<boolean>;
    updateRig(input: RigUpdateInput | null): Promise<Rig | null>;
    updateTandemMainCanopyJumps(input: TandemCanopyJumpsInput): Promise<boolean>;
}
import type { AAD as _AAD, ExternalBlob as _ExternalBlob, FiftyJumpCheck as _FiftyJumpCheck, HarnessContainer as _HarnessContainer, MainCanopy as _MainCanopy, MainCanopyInput as _MainCanopyInput, PackJob as _PackJob, ReserveCanopy as _ReserveCanopy, Rig as _Rig, RigComponents as _RigComponents, RigId as _RigId, RigUpdateInput as _RigUpdateInput, RiggerNote as _RiggerNote, TandemCanopyInput as _TandemCanopyInput, TandemMainCanopy as _TandemMainCanopy, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addHarnessImage(arg0: RigId, arg1: ExternalBlob): Promise<HarnessContainer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addHarnessImage(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHarnessImage(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async addPackJob(arg0: RigId, arg1: string, arg2: string, arg3: string): Promise<PackJob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addPackJob(arg0, arg1, arg2, arg3);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPackJob(arg0, arg1, arg2, arg3);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async addRiggerNote(arg0: RigId, arg1: string, arg2: string): Promise<RiggerNote | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addRiggerNote(arg0, arg1, arg2);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRiggerNote(arg0, arg1, arg2);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeFiftyJumpCheck(arg0: FiftyJumpCheckInput): Promise<FiftyJumpCheck | null> {
        if (this.processError) {
            try {
                const result = await this.actor.completeFiftyJumpCheck(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeFiftyJumpCheck(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRig(arg0: string, arg1: string): Promise<Rig> {
        if (this.processError) {
            try {
                const result = await this.actor.createRig(arg0, arg1);
                return from_candid_Rig_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRig(arg0, arg1);
            return from_candid_Rig_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteRig(arg0: RigId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRig(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFiftyJumpChecks(arg0: RigId): Promise<Array<FiftyJumpCheck>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFiftyJumpChecks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFiftyJumpChecks(arg0);
            return result;
        }
    }
    async getPackJobs(arg0: RigId): Promise<Array<PackJob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPackJobs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPackJobs(arg0);
            return result;
        }
    }
    async getRig(arg0: RigId): Promise<Rig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRig(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRig(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRigComponents(arg0: RigId): Promise<RigComponents | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRigComponents(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRigComponents(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRiggerNotes(arg0: RigId): Promise<Array<RiggerNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRiggerNotes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRiggerNotes(arg0);
            return result;
        }
    }
    async getRigs(): Promise<Array<Rig>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRigs();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRigs();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRigsByUser(arg0: string): Promise<Array<Rig>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRigsByUser(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRigsByUser(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeAAD(arg0: RigId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAAD(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAAD(arg0);
            return result;
        }
    }
    async removeHarnessContainer(arg0: RigId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeHarnessContainer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeHarnessContainer(arg0);
            return result;
        }
    }
    async removeMainCanopy(arg0: RigId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMainCanopy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMainCanopy(arg0);
            return result;
        }
    }
    async removeReserveCanopy(arg0: RigId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeReserveCanopy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeReserveCanopy(arg0);
            return result;
        }
    }
    async removeTandemMainCanopy(arg0: RigId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeTandemMainCanopy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeTandemMainCanopy(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setAAD(arg0: AAD): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setAAD(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAAD(arg0);
            return result;
        }
    }
    async setHarnessContainer(arg0: HarnessContainer): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setHarnessContainer(await to_candid_HarnessContainer_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setHarnessContainer(await to_candid_HarnessContainer_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setMainCanopy(arg0: MainCanopyInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setMainCanopy(await to_candid_MainCanopyInput_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMainCanopy(await to_candid_MainCanopyInput_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setReserveCanopy(arg0: ReserveRepackInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setReserveCanopy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setReserveCanopy(arg0);
            return result;
        }
    }
    async setTandemMainCanopy(arg0: TandemCanopyInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setTandemMainCanopy(await to_candid_TandemCanopyInput_n41(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTandemMainCanopy(await to_candid_TandemCanopyInput_n41(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateMainCanopyJumps(arg0: MainCanopyJumpsInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMainCanopyJumps(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMainCanopyJumps(arg0);
            return result;
        }
    }
    async updateRig(arg0: RigUpdateInput | null): Promise<Rig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRig(to_candid_opt_n43(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRig(to_candid_opt_n43(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTandemMainCanopyJumps(arg0: TandemCanopyJumpsInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTandemMainCanopyJumps(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTandemMainCanopyJumps(arg0);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_HarnessContainer_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HarnessContainer): Promise<HarnessContainer> {
    return await from_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function from_candid_MainCanopy_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MainCanopy): Promise<MainCanopy> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_RigComponents_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RigComponents): Promise<RigComponents> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_Rig_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Rig): Promise<Rig> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_TandemMainCanopy_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TandemMainCanopy): Promise<TandemMainCanopy> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PackJob]): PackJob | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RiggerNote]): RiggerNote | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FiftyJumpCheck]): FiftyJumpCheck | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AAD]): AAD | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MainCanopy]): Promise<MainCanopy | null> {
    return value.length === 0 ? null : await from_candid_MainCanopy_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReserveCanopy]): ReserveCanopy | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TandemMainCanopy]): Promise<TandemMainCanopy | null> {
    return value.length === 0 ? null : await from_candid_TandemMainCanopy_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Rig]): Promise<Rig | null> {
    return value.length === 0 ? null : await from_candid_Rig_n19(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RigComponents]): Promise<RigComponents | null> {
    return value.length === 0 ? null : await from_candid_RigComponents_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HarnessContainer]): Promise<HarnessContainer | null> {
    return value.length === 0 ? null : await from_candid_HarnessContainer_n10(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RigId;
    model: string;
    manufacturer: string;
    serialNumber: string;
    dateOfManufacture: string;
    image: [] | [_ExternalBlob];
}): Promise<{
    id: RigId;
    model: string;
    manufacturer: string;
    serialNumber: string;
    dateOfManufacture: string;
    image?: ExternalBlob;
}> {
    return {
        id: value.id,
        model: value.model,
        manufacturer: value.manufacturer,
        serialNumber: value.serialNumber,
        dateOfManufacture: value.dateOfManufacture,
        image: record_opt_to_undefined(await from_candid_opt_n12(_uploadFile, _downloadFile, value.image))
    };
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RigId;
    aad: [] | [_AAD];
    mainCanopy: [] | [_MainCanopy];
    ownerName: string;
    jumpsSinceLastCheck: bigint;
    name: string;
    createdAt: bigint;
    totalJumps: bigint;
    reserveCanopy: [] | [_ReserveCanopy];
    updatedAt: bigint;
    harnessContainer: [] | [_HarnessContainer];
    tandemCanopy: [] | [_TandemMainCanopy];
}): Promise<{
    id: RigId;
    aad?: AAD;
    mainCanopy?: MainCanopy;
    ownerName: string;
    jumpsSinceLastCheck: bigint;
    name: string;
    createdAt: bigint;
    totalJumps: bigint;
    reserveCanopy?: ReserveCanopy;
    updatedAt: bigint;
    harnessContainer?: HarnessContainer;
    tandemCanopy?: TandemMainCanopy;
}> {
    return {
        id: value.id,
        aad: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.aad)),
        mainCanopy: record_opt_to_undefined(await from_candid_opt_n22(_uploadFile, _downloadFile, value.mainCanopy)),
        ownerName: value.ownerName,
        jumpsSinceLastCheck: value.jumpsSinceLastCheck,
        name: value.name,
        createdAt: value.createdAt,
        totalJumps: value.totalJumps,
        reserveCanopy: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.reserveCanopy)),
        updatedAt: value.updatedAt,
        harnessContainer: record_opt_to_undefined(await from_candid_opt_n9(_uploadFile, _downloadFile, value.harnessContainer)),
        tandemCanopy: record_opt_to_undefined(await from_candid_opt_n26(_uploadFile, _downloadFile, value.tandemCanopy))
    };
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RigId;
    manufacturer: string;
    totalJumps: bigint;
    jumpsOnMainRisers: bigint;
    canopyType: string;
    serialNumber: string;
    dateOfManufacture: string;
    image: [] | [_ExternalBlob];
    jumpsOnLineSet: bigint;
}): Promise<{
    id: RigId;
    manufacturer: string;
    totalJumps: bigint;
    jumpsOnMainRisers: bigint;
    canopyType: string;
    serialNumber: string;
    dateOfManufacture: string;
    image?: ExternalBlob;
    jumpsOnLineSet: bigint;
}> {
    return {
        id: value.id,
        manufacturer: value.manufacturer,
        totalJumps: value.totalJumps,
        jumpsOnMainRisers: value.jumpsOnMainRisers,
        canopyType: value.canopyType,
        serialNumber: value.serialNumber,
        dateOfManufacture: value.dateOfManufacture,
        image: record_opt_to_undefined(await from_candid_opt_n12(_uploadFile, _downloadFile, value.image)),
        jumpsOnLineSet: value.jumpsOnLineSet
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RigId;
    manufacturer: string;
    jumpsOnDrogueBridle: bigint;
    totalJumps: bigint;
    jumpsOnMainRisers: bigint;
    canopyType: string;
    serialNumber: string;
    dateOfManufacture: string;
    image: [] | [_ExternalBlob];
    jumpsOnLowerBridleKillLine: bigint;
    jumpsOnLineSet: bigint;
}): Promise<{
    id: RigId;
    manufacturer: string;
    jumpsOnDrogueBridle: bigint;
    totalJumps: bigint;
    jumpsOnMainRisers: bigint;
    canopyType: string;
    serialNumber: string;
    dateOfManufacture: string;
    image?: ExternalBlob;
    jumpsOnLowerBridleKillLine: bigint;
    jumpsOnLineSet: bigint;
}> {
    return {
        id: value.id,
        manufacturer: value.manufacturer,
        jumpsOnDrogueBridle: value.jumpsOnDrogueBridle,
        totalJumps: value.totalJumps,
        jumpsOnMainRisers: value.jumpsOnMainRisers,
        canopyType: value.canopyType,
        serialNumber: value.serialNumber,
        dateOfManufacture: value.dateOfManufacture,
        image: record_opt_to_undefined(await from_candid_opt_n12(_uploadFile, _downloadFile, value.image)),
        jumpsOnLowerBridleKillLine: value.jumpsOnLowerBridleKillLine,
        jumpsOnLineSet: value.jumpsOnLineSet
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aad: [] | [_AAD];
    mainCanopy: [] | [_MainCanopy];
    reserveCanopy: [] | [_ReserveCanopy];
    harnessContainer: [] | [_HarnessContainer];
    tandemCanopy: [] | [_TandemMainCanopy];
}): Promise<{
    aad?: AAD;
    mainCanopy?: MainCanopy;
    reserveCanopy?: ReserveCanopy;
    harnessContainer?: HarnessContainer;
    tandemCanopy?: TandemMainCanopy;
}> {
    return {
        aad: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.aad)),
        mainCanopy: record_opt_to_undefined(await from_candid_opt_n22(_uploadFile, _downloadFile, value.mainCanopy)),
        reserveCanopy: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.reserveCanopy)),
        harnessContainer: record_opt_to_undefined(await from_candid_opt_n9(_uploadFile, _downloadFile, value.harnessContainer)),
        tandemCanopy: record_opt_to_undefined(await from_candid_opt_n26(_uploadFile, _downloadFile, value.tandemCanopy))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Rig>): Promise<Array<Rig>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Rig_n19(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_HarnessContainer_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HarnessContainer): Promise<_HarnessContainer> {
    return await to_candid_record_n38(_uploadFile, _downloadFile, value);
}
async function to_candid_MainCanopyInput_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MainCanopyInput): Promise<_MainCanopyInput> {
    return await to_candid_record_n40(_uploadFile, _downloadFile, value);
}
async function to_candid_TandemCanopyInput_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TandemCanopyInput): Promise<_TandemCanopyInput> {
    return await to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RigUpdateInput | null): [] | [_RigUpdateInput] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: RigId;
    model: string;
    manufacturer: string;
    serialNumber: string;
    dateOfManufacture: string;
    image?: ExternalBlob;
}): Promise<{
    id: _RigId;
    model: string;
    manufacturer: string;
    serialNumber: string;
    dateOfManufacture: string;
    image: [] | [_ExternalBlob];
}> {
    return {
        id: value.id,
        model: value.model,
        manufacturer: value.manufacturer,
        serialNumber: value.serialNumber,
        dateOfManufacture: value.dateOfManufacture,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.image)) : candid_none()
    };
}
async function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: RigId;
    manufacturer: string;
    totalJumps: bigint;
    jumpsOnMainRisers: bigint;
    canopyType: string;
    serialNumber: string;
    dateOfManufacture: string;
    image?: ExternalBlob;
    jumpsOnLineSet: bigint;
}): Promise<{
    id: _RigId;
    manufacturer: string;
    totalJumps: bigint;
    jumpsOnMainRisers: bigint;
    canopyType: string;
    serialNumber: string;
    dateOfManufacture: string;
    image: [] | [_ExternalBlob];
    jumpsOnLineSet: bigint;
}> {
    return {
        id: value.id,
        manufacturer: value.manufacturer,
        totalJumps: value.totalJumps,
        jumpsOnMainRisers: value.jumpsOnMainRisers,
        canopyType: value.canopyType,
        serialNumber: value.serialNumber,
        dateOfManufacture: value.dateOfManufacture,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.image)) : candid_none(),
        jumpsOnLineSet: value.jumpsOnLineSet
    };
}
async function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: RigId;
    manufacturer: string;
    jumpsOnDrogueBridle: bigint;
    totalJumps: bigint;
    jumpsOnMainRisers: bigint;
    canopyType: string;
    serialNumber: string;
    dateOfManufacture: string;
    image?: ExternalBlob;
    jumpsOnLowerBridleKillLine: bigint;
    jumpsOnLineSet: bigint;
}): Promise<{
    id: _RigId;
    manufacturer: string;
    jumpsOnDrogueBridle: bigint;
    totalJumps: bigint;
    jumpsOnMainRisers: bigint;
    canopyType: string;
    serialNumber: string;
    dateOfManufacture: string;
    image: [] | [_ExternalBlob];
    jumpsOnLowerBridleKillLine: bigint;
    jumpsOnLineSet: bigint;
}> {
    return {
        id: value.id,
        manufacturer: value.manufacturer,
        jumpsOnDrogueBridle: value.jumpsOnDrogueBridle,
        totalJumps: value.totalJumps,
        jumpsOnMainRisers: value.jumpsOnMainRisers,
        canopyType: value.canopyType,
        serialNumber: value.serialNumber,
        dateOfManufacture: value.dateOfManufacture,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.image)) : candid_none(),
        jumpsOnLowerBridleKillLine: value.jumpsOnLowerBridleKillLine,
        jumpsOnLineSet: value.jumpsOnLineSet
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
